// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220718193932_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocalId")
                        .HasColumnType("int");

                    b.Property<int>("LocalScore")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<int>("VisitScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("VisitId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "E",
                            Date = new DateTime(2022, 12, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 18,
                            LocalScore = 0,
                            VisitId = 19,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "F",
                            Date = new DateTime(2022, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 24,
                            LocalScore = 0,
                            VisitId = 21,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "F",
                            Date = new DateTime(2022, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 22,
                            LocalScore = 0,
                            VisitId = 23,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "E",
                            Date = new DateTime(2022, 12, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 20,
                            LocalScore = 0,
                            VisitId = 17,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 5,
                            Code = "G",
                            Date = new DateTime(2022, 12, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 28,
                            LocalScore = 0,
                            VisitId = 25,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 6,
                            Code = "G",
                            Date = new DateTime(2022, 12, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 26,
                            LocalScore = 0,
                            VisitId = 27,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 7,
                            Code = "H",
                            Date = new DateTime(2022, 12, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 32,
                            LocalScore = 0,
                            VisitId = 29,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 8,
                            Code = "H",
                            Date = new DateTime(2022, 12, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 30,
                            LocalScore = 0,
                            VisitId = 31,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 9,
                            Code = "A",
                            Date = new DateTime(2022, 11, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 1,
                            LocalScore = 0,
                            VisitId = 2,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 10,
                            Code = "A",
                            Date = new DateTime(2022, 11, 21, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 3,
                            LocalScore = 0,
                            VisitId = 4,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 11,
                            Code = "B",
                            Date = new DateTime(2022, 11, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 5,
                            LocalScore = 0,
                            VisitId = 6,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 12,
                            Code = "B",
                            Date = new DateTime(2022, 11, 21, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 7,
                            LocalScore = 0,
                            VisitId = 8,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 13,
                            Code = "C",
                            Date = new DateTime(2022, 11, 22, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 9,
                            LocalScore = 0,
                            VisitId = 10,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 14,
                            Code = "C",
                            Date = new DateTime(2022, 11, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 11,
                            LocalScore = 0,
                            VisitId = 12,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 15,
                            Code = "D",
                            Date = new DateTime(2022, 11, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 13,
                            LocalScore = 0,
                            VisitId = 14,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 16,
                            Code = "D",
                            Date = new DateTime(2022, 11, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 15,
                            LocalScore = 0,
                            VisitId = 16,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 17,
                            Code = "E",
                            Date = new DateTime(2022, 11, 23, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 17,
                            LocalScore = 0,
                            VisitId = 18,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 18,
                            Code = "E",
                            Date = new DateTime(2022, 11, 23, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 19,
                            LocalScore = 0,
                            VisitId = 20,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 19,
                            Code = "F",
                            Date = new DateTime(2022, 11, 23, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 21,
                            LocalScore = 0,
                            VisitId = 22,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 20,
                            Code = "F",
                            Date = new DateTime(2022, 11, 23, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 23,
                            LocalScore = 0,
                            VisitId = 24,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 21,
                            Code = "G",
                            Date = new DateTime(2022, 11, 24, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 25,
                            LocalScore = 0,
                            VisitId = 26,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 22,
                            Code = "G",
                            Date = new DateTime(2022, 11, 24, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 27,
                            LocalScore = 0,
                            VisitId = 28,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 23,
                            Code = "H",
                            Date = new DateTime(2022, 11, 24, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 29,
                            LocalScore = 0,
                            VisitId = 30,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 24,
                            Code = "H",
                            Date = new DateTime(2022, 11, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 31,
                            LocalScore = 0,
                            VisitId = 32,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 25,
                            Code = "A",
                            Date = new DateTime(2022, 11, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 1,
                            LocalScore = 0,
                            VisitId = 3,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 26,
                            Code = "A",
                            Date = new DateTime(2022, 11, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 4,
                            LocalScore = 0,
                            VisitId = 2,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 27,
                            Code = "B",
                            Date = new DateTime(2022, 11, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 5,
                            LocalScore = 0,
                            VisitId = 7,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 28,
                            Code = "B",
                            Date = new DateTime(2022, 11, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 8,
                            LocalScore = 0,
                            VisitId = 6,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 29,
                            Code = "C",
                            Date = new DateTime(2022, 11, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 9,
                            LocalScore = 0,
                            VisitId = 11,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 30,
                            Code = "C",
                            Date = new DateTime(2022, 11, 26, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 12,
                            LocalScore = 0,
                            VisitId = 10,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 31,
                            Code = "D",
                            Date = new DateTime(2022, 11, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 13,
                            LocalScore = 0,
                            VisitId = 15,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 32,
                            Code = "D",
                            Date = new DateTime(2022, 11, 26, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 16,
                            LocalScore = 0,
                            VisitId = 14,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 33,
                            Code = "E",
                            Date = new DateTime(2022, 11, 27, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 17,
                            LocalScore = 0,
                            VisitId = 19,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 34,
                            Code = "E",
                            Date = new DateTime(2022, 11, 27, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 20,
                            LocalScore = 0,
                            VisitId = 18,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 35,
                            Code = "F",
                            Date = new DateTime(2022, 11, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 21,
                            LocalScore = 0,
                            VisitId = 23,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 36,
                            Code = "F",
                            Date = new DateTime(2022, 11, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 24,
                            LocalScore = 0,
                            VisitId = 22,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 37,
                            Code = "G",
                            Date = new DateTime(2022, 11, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 25,
                            LocalScore = 0,
                            VisitId = 27,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 38,
                            Code = "G",
                            Date = new DateTime(2022, 11, 28, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 28,
                            LocalScore = 0,
                            VisitId = 26,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 39,
                            Code = "H",
                            Date = new DateTime(2022, 11, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 29,
                            LocalScore = 0,
                            VisitId = 31,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 40,
                            Code = "H",
                            Date = new DateTime(2022, 11, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 32,
                            LocalScore = 0,
                            VisitId = 30,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 41,
                            Code = "A",
                            Date = new DateTime(2022, 11, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 4,
                            LocalScore = 0,
                            VisitId = 1,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 42,
                            Code = "A",
                            Date = new DateTime(2022, 11, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 2,
                            LocalScore = 0,
                            VisitId = 3,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 43,
                            Code = "B",
                            Date = new DateTime(2022, 11, 29, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 8,
                            LocalScore = 0,
                            VisitId = 5,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 44,
                            Code = "B",
                            Date = new DateTime(2022, 11, 29, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 6,
                            LocalScore = 0,
                            VisitId = 7,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 45,
                            Code = "C",
                            Date = new DateTime(2022, 11, 30, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 12,
                            LocalScore = 0,
                            VisitId = 9,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 46,
                            Code = "C",
                            Date = new DateTime(2022, 11, 30, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 10,
                            LocalScore = 0,
                            VisitId = 11,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 47,
                            Code = "D",
                            Date = new DateTime(2022, 11, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 16,
                            LocalScore = 0,
                            VisitId = 13,
                            VisitScore = 0
                        },
                        new
                        {
                            Id = 48,
                            Code = "D",
                            Date = new DateTime(2022, 11, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            LocalId = 14,
                            LocalScore = 0,
                            VisitId = 15,
                            VisitScore = 0
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocalScore")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VisitScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Dominio.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Group = "A",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Group = "A",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Group = "A",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Group = "A",
                            Name = "Países Bajos"
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Group = "B",
                            Name = "Inglaterra"
                        },
                        new
                        {
                            Id = 6,
                            Deleted = false,
                            Group = "B",
                            Name = "Irán"
                        },
                        new
                        {
                            Id = 7,
                            Deleted = false,
                            Group = "B",
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = 8,
                            Deleted = false,
                            Group = "B",
                            Name = "Gales"
                        },
                        new
                        {
                            Id = 9,
                            Deleted = false,
                            Group = "C",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 10,
                            Deleted = false,
                            Group = "C",
                            Name = "Arabia Saudita"
                        },
                        new
                        {
                            Id = 11,
                            Deleted = false,
                            Group = "C",
                            Name = "México"
                        },
                        new
                        {
                            Id = 12,
                            Deleted = false,
                            Group = "C",
                            Name = "Polonia"
                        },
                        new
                        {
                            Id = 13,
                            Deleted = false,
                            Group = "D",
                            Name = "Francia"
                        },
                        new
                        {
                            Id = 14,
                            Deleted = false,
                            Group = "D",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Deleted = false,
                            Group = "D",
                            Name = "Dinamarca"
                        },
                        new
                        {
                            Id = 16,
                            Deleted = false,
                            Group = "D",
                            Name = "Túnez"
                        },
                        new
                        {
                            Id = 17,
                            Deleted = false,
                            Group = "E",
                            Name = "España"
                        },
                        new
                        {
                            Id = 18,
                            Deleted = false,
                            Group = "E",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 19,
                            Deleted = false,
                            Group = "E",
                            Name = "Alemania"
                        },
                        new
                        {
                            Id = 20,
                            Deleted = false,
                            Group = "E",
                            Name = "Japón"
                        },
                        new
                        {
                            Id = 21,
                            Deleted = false,
                            Group = "F",
                            Name = "Bélgica"
                        },
                        new
                        {
                            Id = 22,
                            Deleted = false,
                            Group = "F",
                            Name = "Canadá"
                        },
                        new
                        {
                            Id = 23,
                            Deleted = false,
                            Group = "F",
                            Name = "Marruecos"
                        },
                        new
                        {
                            Id = 24,
                            Deleted = false,
                            Group = "F",
                            Name = "Croacia"
                        },
                        new
                        {
                            Id = 25,
                            Deleted = false,
                            Group = "G",
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = 26,
                            Deleted = false,
                            Group = "G",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 27,
                            Deleted = false,
                            Group = "G",
                            Name = "Suiza"
                        },
                        new
                        {
                            Id = 28,
                            Deleted = false,
                            Group = "G",
                            Name = "Camerún"
                        },
                        new
                        {
                            Id = 29,
                            Deleted = false,
                            Group = "H",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 30,
                            Deleted = false,
                            Group = "H",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 31,
                            Deleted = false,
                            Group = "H",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 32,
                            Deleted = false,
                            Group = "H",
                            Name = "Corea"
                        });
                });

            modelBuilder.Entity("Dominio.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dominio.Entities.Match", b =>
                {
                    b.HasOne("Dominio.Entities.Team", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Team", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dominio.Entities.Prediction", b =>
                {
                    b.HasOne("Dominio.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dominio.Entities.User", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
